/* ================================================================
   cards.js — Card Database (Templates)
   
   Dynamically populated from cards_data.json.
   Each card features unique artwork generated by mflux.
   ================================================================ */

// This will be populated during initialization
let CARD_TEMPLATES = [];

/**
 * Loads card data from cards_data.json and populates CARD_TEMPLATES.
 * This is called during the game initialization process.
 */
async function loadCardTemplates() {
    try {
        const response = await fetch('cards_data.json');
        if (!response.ok) {
            throw new Error(`Failed to load cards_data.json: ${response.statusText}`);
        }
        const data = await response.json();
        
        // Transform the data into the format expected by the game
        CARD_TEMPLATES = data.cards.map(card => {
            // Determine image path from the filename in card_prompts
            // The image generation script saves .png files in the 'cards/' folder
            // with the same base name as the prompt .txt files.
            const promptFileName = card.artwork_prompt_file.split('/').pop();
            const imageFileName = promptFileName.replace('.txt', '.png');
            const imagePath = `cards/${imageFileName}`;

            return {
                id: card.id,
                name: card.name,
                manaCost: card.mana_cost,
                attack: card.attack,
                health: card.health,
                typeLine: card.type_line,
                mythology: card.mythology,
                rarity: card.rarity,
                abilities: card.abilities,
                // Flatten abilities for display
                ability: card.abilities[0] || "",
                abilityDesc: card.abilities.join('\n'),
                image: imagePath,
                template: card.template
            };
        });

        console.log(`Loaded ${CARD_TEMPLATES.length} card templates.`);
        return true;
    } catch (error) {
        console.error("Error loading card templates:", error);
        // Fallback to minimal set if loading fails
        CARD_TEMPLATES = [
            { name: "Error Loading Cards", manaCost: 0, attack: 1, health: 1, mythology: "Unknown", ability: "Check Console", abilityDesc: error.message, image: "" }
        ];
        return false;
    }
}
